### ISSUE TITLE
swift 3 support 

### ISSUE THREAD

**Issue by Ahmedshubber** [stripe/ios-dashboard-ui#1]
Hello, may I just say this is a great project. But there is one problem. Could you update this to swift 3.0.

**Comment by Mr-Paradox** [comment]
Hello world. I am

**Comment by bg-stripe** [comment]
hey folks, sorry about the long delay for swift 3 support! we've updated to swift 3 in the [latest release](https://github.com/stripe/ios-dashboard-ui/releases/tag/0.2)
