### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by schenkty** [stripe/ios-dashboard-ui#2]
Hey, will there be any support for Swift 4? I would love to use this in one of my apps.

Thank you

**Comment by joeydong-stripe** [comment]
Looks like @ranesr kindly fulfilled this one! I've created a new release `0.3` so upgrade to that for Swift 4. https://github.com/stripe/ios-dashboard-ui/releases

**Comment by tcatwork** [comment]
Hi @joeydong-stripe - Thank you for your work on this project! Do you have plans to publish `0.3` as a cocoapod?

**Comment by joeydong-stripe** [comment]
Oh, hmm, let me investigate.

**Comment by joeydong-stripe** [comment]
Hi @tcatwork, you were right! I just wrote a note to ourselves to make sure we don't forget next time. You should see `0.3` on CocoaPods now. Sorry about that and thanks for letting us know 😄

**Comment by tcatwork** [comment]
Thank you so much, @joeydong-stripe!! 🥇It worked like a charm.
